[package]
name = "lexical_write_float_benchmark"
version = "0.0.1"
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
edition = "2018"
publish = false

[dependencies.lexical_write_float]
path = "../../lexical_write_float"
default-features = false
features = []

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[features]
std = ["lexical_write_float/std"]
radix = ["lexical_write_float/radix"]
power_of_two = ["lexical_write_float/power_of_two"]

[[bench]]
name = "write_integer"
path = "bench.rs"
harness = false
