[package]
name = "lexical_parse_integer_benchmark"
version = "0.0.1"
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
edition = "2018"
publish = false

[dependencies.lexical_parse_integer]
path = "../../lexical_parse_integer"
default-features = false
features = []

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[features]
std = ["lexical_parse_integer/std"]
radix = ["lexical_parse_integer/radix"]
power_of_two = ["lexical_parse_integer/power_of_two"]

[[bench]]
name = "write_integer"
path = "bench.rs"
harness = false
