sudo: false

language: rust

matrix:
  include:
    - rust: stable
    - rust: beta

    - rust: nightly
      script:
        - cargo test
        - cargo test --no-default-features
        - cargo test --no-default-features --features=alloc
        - cargo test --no-default-features --features=alloc,table
        - cargo test --no-default-features --features=alloc,table,grisu3
        - cargo test --no-default-features --features=alloc,table,ryu

script:
  - cargo build
  - cargo test
  - cargo test --no-default-features --features=std,table
  - cargo test --no-default-features --features=std,table,grisu3
  - cargo test --no-default-features --features=std,table,ryu
