sudo: false

language: rust

matrix:
  include:
    - rust: stable
    - rust: beta

    - rust: nightly
      script:
        - cargo build
        - cargo test
        - cd lexical-core
        - cargo test
        - cargo test --no-default-features --tests
        - cargo test --no-default-features --features=trim_floats --tests
        - cargo test --no-default-features --features=trim_floats,radix --tests
        - cargo test --no-default-features --features=trim_floats,unchecked_index --tests
        - cargo test --no-default-features --features=table --tests
        - cargo test --no-default-features --features=table,radix --tests
        - cargo test --no-default-features --features=table,unchecked_index --tests
        - cargo test --no-default-features --features=grisu3 --tests
        - cargo test --no-default-features --features=ryu --tests
        - cargo test --no-default-features --features=correct --tests
        - cargo test --no-default-features --features=correct,radix --tests
        - cargo test --no-default-features --features=correct,unchecked_index --tests
        - cargo test --no-default-features --features=correct,radix --tests special_rounding -- --ignored --test-threads=1
        - cd ..
        - cargo bench --verbose --no-run

script:
  - cargo build
  - cargo test
  - cd lexical-core
  - cargo test --features=std
  - cargo test --no-default-features --features=std
  - cargo test --no-default-features --features=std,trim_floats
  - cargo test --no-default-features --features=std,trim_floats,radix
  - cargo test --no-default-features --features=std,trim_floats,unchecked_index
  - cargo test --no-default-features --features=std,table
  - cargo test --no-default-features --features=std,table,radix
  - cargo test --no-default-features --features=std,table,unchecked_index
  - cargo test --no-default-features --features=std,grisu3
  - cargo test --no-default-features --features=std,ryu
  - cargo test --no-default-features --features=std,correct
  - cargo test --no-default-features --features=std,correct,radix
  - cargo test --no-default-features --features=std,correct,unchecked_index
  - cargo test --features=radix special_rounding -- --ignored --test-threads=1
  - cd ..
  - cargo bench --verbose --no-run
