sudo: false

language: rust

matrix:
  include:
    - rust: stable
    - rust: beta

    - rust: nightly
      script:
        - cargo test
        - cargo test --no-default-features
        - cargo test --no-default-features --features=grisu3
        - cargo test --no-default-features --features=ryu
        - cargo test --no-default-features --features=table
        - cargo test --no-default-features --features=table,grisu3
        - cargo test --no-default-features --features=table,ryu
        - cargo test --no-default-features --features=imprecise
        - cargo test --no-default-features --features=imprecise,grisu3
        - cargo test --no-default-features --features=imprecise,ryu
        - cargo test --no-default-features --features=imprecise,table
        - cargo test --no-default-features --features=imprecise,table,grisu3
        - cargo test --no-default-features --features=imprecise,table,ryu

script:
  - cargo build
  - cargo test
  - cargo test --no-default-features --features=std,table
  - cargo test --no-default-features --features=std,table,grisu3
  - cargo test --no-default-features --features=std,table,ryu
  - cargo test --no-default-features --features=std,imprecise,table
  - cargo test --no-default-features --features=std,imprecise,table,grisu3
  - cargo test --no-default-features --features=std,imprecise,table,ryu
