[package]
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
categories = ["parsing", "encoding"]
description = "Lexical, to- and from-string conversion routines."
documentation = "https://docs.rs/lexical"
keywords = ["parsing", "lexical", "encoding"]
license = "MIT/Apache-2.0"
name = "lexical"
readme = "README.md"
repository = "https://github.com/AlexHuszagh/rust-lexical"
version = "0.0.1"

[badges]
travis-ci = { repository = "AlexHuszagh/rust-lexical" }

[dependencies]
# Global allocator only used during testing.
wee_alloc = { version = "0.4", optional = true }

[dev-dependencies]
bencher = "0.1.5"

[features]
default = ["std"]
alloc = ["wee_alloc"]
std = []
nightly = ["alloc"]

# Benchmarks

[[bench]]
name = "itoa"
harness = false

[profile.bench]
opt-level = 3
lto = true
