[package]
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
autobenches = false
categories = ["parsing", "encoding"]
description = "Lexical, to- and from-string conversion routines."
documentation = "https://docs.rs/lexical"
keywords = ["parsing", "lexical", "encoding"]
license = "MIT/Apache-2.0"
name = "lexical"
readme = "README.md"
repository = "https://github.com/Alexhuszagh/rust-lexical"
version = "1.6.7"
exclude = [
    "data/*",
    "benches/*",
]

[badges]
travis-ci = { repository = "Alexhuszagh/rust-lexical" }

[dependencies]
cfg-if = "0.1"
static_assertions = "0.2.5"
# Use small-vector optimization for Bigfloat class.
# TODO(ahuszagh) Remove...
smallvec = "0.6"
# Use stack-vector for dtoa.
stackvector = "^1.0.1"
# Optimized Grisu3 implementation, a well-tested, correct algorithm.
dtoa = { version = "0.4", optional = true }
# Optimized Ryu implementation, the fastest correct algorithm.
ryu = { version = "^0.2.7", optional = true }
# The following are only required for comprehensive float unittests.
# IE, internal testing only:
rand = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
toml = { version = "0.4", optional = true }

[dev-dependencies]
approx = "0.3.0"
bencher = "0.1.5"
dtoa = "0.4"
itoa = "0.4"
lazy_static = "1"
quickcheck = "0.7"
ryu = "0.2"

[features]
default = ["ryu", "std", "table"]
# Use the optimized Grisu3 implementation from dtoa (not recommended).
grisu3 = ["dtoa"]
# Use the imprecise atof functionality with an intermediate float (unsupported as of now).
imprecise = []
# Use the `std` library.
std = []
# Use precompiled tables for faster performance and accuracy, at the cost of larger binaries.
# You should never disable table with precise.
table = []
# Build the comprehensive float parsing tests.
comprehensive_float_test = ["rand/std", "serde/std", "serde_derive", "std", "toml"]

# Binaries
# Special testing binaries for the runtests.py scripts.

[[bin]]
name = "few_ones"
path = "data/test-float-parse/few_ones.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "huge-pow10"
path = "data/test-float-parse/huge-pow10.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "long-fractions"
path = "data/test-float-parse/long-fractions.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "many-digits"
path = "data/test-float-parse/many-digits.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "rand-f64"
path = "data/test-float-parse/rand-f64.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "short-decimals"
path = "data/test-float-parse/short-decimals.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "subnorm"
path = "data/test-float-parse/subnorm.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "tiny-pow10"
path = "data/test-float-parse/tiny-pow10.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "u32-small"
path = "data/test-float-parse/u32-small.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "u64-pow2"
path = "data/test-float-parse/u64-pow2.rs"
required-features = ["comprehensive_float_test"]

[[bin]]
name = "test-strtod"
path = "data/test-strtod/main.rs"
required-features = ["comprehensive_float_test"]

# Benchmarks

[[bench]]
name = "atof"
harness = false

[[bench]]
name = "atof_digits2"
harness = false

[[bench]]
name = "atof_digits8"
harness = false

[[bench]]
name = "atof_digits16"
harness = false

[[bench]]
name = "atof_digits32"
harness = false

[[bench]]
name = "atof_digits64"
harness = false

[[bench]]
name = "atof_malicious"
harness = false

[[bench]]
name = "atof_real"
harness = false

[[bench]]
name = "atof_stress"
harness = false

[[bench]]
name = "atoi"
harness = false

[[bench]]
name = "bigfloat"
harness = false

[[bench]]
name = "itoa"
harness = false

[[bench]]
name = "ftoa"
harness = false

[profile.bench]
opt-level = 3
lto = true
