[package]
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
autobenches = false
categories = ["parsing", "encoding"]
description = "Lexical, to- and from-string conversion routines."
documentation = "https://docs.rs/lexical"
keywords = ["parsing", "lexical", "encoding"]
license = "MIT/Apache-2.0"
name = "lexical"
readme = "README.md"
repository = "https://github.com/Alexhuszagh/rust-lexical"
version = "1.3.1"
exclude = [
    "benches/*",
]

[badges]
travis-ci = { repository = "Alexhuszagh/rust-lexical" }

[dependencies]
# Global allocator only used during testing.
wee_alloc = { version = "0.4", optional = true }

[dev-dependencies]
approx = "0.3.0"
bencher = "0.1.5"
dtoa = "0.4"
itoa = "0.4"

[features]
default = ["std", "table"]
alloc = ["wee_alloc"]
nightly = ["alloc"]
# Use the `std` library.
std = []
# Use precompiled tables for faster performance, at the cost of larger binaries.
table = []

# Benchmarks

[[bench]]
name = "atof"
harness = false

[[bench]]
name = "atoi"
harness = false

[[bench]]
name = "itoa"
harness = false

[[bench]]
name = "ftoa"
harness = false

[profile.bench]
opt-level = 3
lto = true
