[package]
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
autobenches = false
categories = ["parsing", "no-std"]
description = "Efficient parsing of integers from strings."
edition = "2018"
keywords = ["parsing", "lexical", "no_std"]
license = "MIT/Apache-2.0"
name = "lexical-parse-integer"
readme = "README.md"
repository = "https://github.com/Alexhuszagh/rust-lexical-experimental"
version = "0.1.0"

[dependencies.lexical-util]
version = "0.1"
path = "../lexical-util"
features = ["parse-integers"]

[features]
default = ["std"]
# Use the standard library.
std = []
# Add support for parsing power-of-two integer strings.
power-of-two = ["lexical-util/power-of-two"]
# Add support for parsing non-decimal integer strings.
radix = ["lexical-util/radix", "power-of-two"]

# Internal only features.
# Enable the lint checks.
lint = []
