[package]
name = "lexical-benchmark"
version = "0.0.1"
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
publish = false

[dependencies.lexical-core]
path = "../../lexical-core"
default-features = false
features = ["correct", "ryu", "std"]

[dev-dependencies]
bencher = "0.1.5"
lazy_static = "1"
serde_json = "1.0"

[features]
default = []
noinline = ["lexical-core/noinline"]
unchecked_index = ["lexical-core/unchecked_index"]

[[bench]]
name = "atof"
harness = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
lto = true
