[package]
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
autobenches = false
categories = ["parsing", "encoding", "no-std", "value-formatting"]
description = "Lexical, to- and from-string conversion routines."
edition = "2018"
keywords = ["parsing", "lexical", "encoding", "no_std"]
license = "MIT/Apache-2.0"
name = "lexical"
readme = "README.md"
repository = "https://github.com/Alexhuszagh/rust-lexical-experimental"
version = "0.1.0"

[dependencies.lexical-core]
version = "0.1"
optional = true
path = "../lexical-core"

[features]
default = ["std"]
# Use the standard library.
std = []
# Add support for writing integers.
write-integers = ["lexical-core/write-integers"]
# Add support for writing floats.
write-floats = ["lexical-core/write-floats"]
# Add support for parsing integers.
parse-integers = ["lexical-core/parse-integers"]
# Add support for parsing floats.
parse-floats = ["lexical-core/parse-floats"]
# Add support for parsing power-of-two float strings.
power-of-two = ["lexical-core/power-of-two"]
# Add support for parsing non-decimal float strings.
radix = ["lexical-core/radix"]

# Internal only features.
# Enable the lint checks.
lint = ["lexical-core/lint"]
