[package]
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
autobenches = false
categories = ["parsing", "encoding", "no-std"]
description = "Lexical, to- and from-string conversion routines."
documentation = "https://docs.rs/lexical-core"
keywords = ["parsing", "lexical", "encoding", "no_std"]
license = "MIT/Apache-2.0"
name = "lexical-core"
readme = "README.md"
repository = "https://github.com/Alexhuszagh/rust-lexical/tree/master/lexical-core"
version = "0.1.3"

[badges]
travis-ci = { repository = "Alexhuszagh/rust-lexical" }

[dependencies]
cfg-if = "0.1"
static_assertions = "0.2.5"
# Use stack-vector for the correct parser.
stackvector = { version = "^1.0.1", optional = true }
# Optimized Grisu3 implementation, a well-tested, correct algorithm.
dtoa = { version = "0.4", optional = true }
# Optimized Ryu implementation, the fastest correct algorithm.
ryu = { version = "^0.2.7", optional = true }

[dev-dependencies]
approx = "0.3.0"
quickcheck = "0.7"
proptest = "0.8.7"

[features]
default = ["correct", "ryu", "std"]
# Use algorithm M, which requires a system allocator.
algorithm_m = ["correct"]
# Use the correct atof parser.
correct = ["stackvector", "table"]
# Use the optimized Grisu3 implementation from dtoa (not recommended).
grisu3 = ["dtoa"]
# Add support for [parsing non-decimal float and integer strings.
radix = []
# Use the `std` library.
std = []
# Use precompiled tables for faster performance and accuracy, at the cost of larger binaries.
table = []
# Trim a trailing ".0" from an exported float string, and represent -0.0 as "0".
trim_floats = []

# Use heavy optimizations for release builds, and make our panics to detect
# internal logic errors safe for FFI, via abort.
[profile.dev]
opt-level = 0
debug = true
lto = false
panic = 'abort'

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = true
panic = 'abort'
