[package]
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
autobenches = false
categories = ["parsing", "no-std"]
description = "Efficient parsing of floats from strings."
edition = "2018"
keywords = ["parsing", "lexical", "no_std"]
license = "MIT/Apache-2.0"
name = "lexical-parse-float"
readme = "README.md"
repository = "https://github.com/Alexhuszagh/rust-lexical-experimental"
version = "0.1.0"
exclude = [
    "assets/*",
    "cargo-timing*.html"
]

[dependencies.lexical-util]
version = "0.1"
path = "../lexical-util"
features = ["parse-floats"]

[features]
default = ["std"]
# Use the standard library.
std = []
# Add support for parsing power-of-two float strings.
power-of-two = ["lexical-util/power-of-two"]
# Add support for parsing non-decimal float strings.
radix = ["lexical-util/radix", "power-of-two"]
# Add support for parsing custom float formats.
format = ["lexical-util/format"]
# Reduce code size at the cost of performance.
compact = ["lexical-util/compact"]

# Internal only features.
# Enable the lint checks.
lint = []
