[package]
name = "minimal-lexical-benchmark"
version = "0.0.1"
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
publish = false

[dependencies.minimal-lexical]
git = "https://github.com/Alexhuszagh/minimal-lexical"
branch = "stable"
default-features = false
features = ["no_alloc"]

[dev-dependencies]
criterion = "0.3"
lazy_static = "1"
serde_json = "1.0"

[features]
default = ["std"]
std = ["minimal-lexical/std"]
no_alloc = ["minimal-lexical/no_alloc"]

[[bench]]
name = "atof"
path = "benches/atof.rs"
harness = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
lto = true
