[package]
name = "lexical_write_integer_benchmark"
version = "0.0.1"
authors = ["Alex Huszagh <ahuszagh@gmail.com>"]
edition = "2018"
publish = false

[dependencies.lexical_util]
path = "../../lexical_util"
default-features = false
features = []

[dependencies.lexical_write_integer]
path = "../../lexical_write_integer"
default-features = false
features = []

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
itoa = { version = "0.4", features = ["i128"] }
fastrand = "1.4"
lazy_static = "1"

[features]
default = ["std"]
std = ["lexical_util/std", "lexical_write_integer/std"]
radix = ["lexical_util/radix", "lexical_write_integer/radix"]
power_of_two = ["lexical_util/power_of_two", "lexical_write_integer/power_of_two"]

[[bench]]
name = "json"
path = "json.rs"
harness = false

[[bench]]
name = "random"
path = "random.rs"
harness = false
